spring:
  application:
    name: notification
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  #    import: "configserver:http://localhost:18080"
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 19098

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:19090/eureka/

#message: "default message" # config server? ???? ?? ?

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh

slack:
  bot-token: ${SLACK_BOT_TOKEN}